config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'store#index', as: 'store_index'
  #get 'store/index'
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    validates :title, :description, :image_url, presence: true 
    validates :title, uniqueness: true
    validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
    }
    validates :price, numericality: { greater_than_or_equal_to: 0.01 }    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf:"PDF-de-#{@project.id}",
        header: {
          center: "Proyectos Juan Carlos Guerrero"
        },
        footer: {
          center: "www.jclatam.com"
        },
        layout: '/store/index.html.erb',
        page_size: 'legal',
        file:'/projects/show.pdf.erb'
      end
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :image_url, :price)
    end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @projects = Project.order(:title)
  end
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf:"PDF-de-#{@project.id}",
        header: {
          center: "Proyectos Juan Carlos Guerrero"
        },
        footer: {
          center: "www.jclatam.com"
        },
        layout: '/store/index.html.erb',
        page_size: 'legal',
        file:'/projects/show.pdf.erb'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<title>Proyectos de Dev Soft  & Virtualización de Cursos </title>
<meta name="viewport" content="width=device-width,initial-scale=1"> 
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
  <p>Ha ingresado como: <%= current_user.email %></p>
  <%= link_to current_user.email, edit_user_registration_path %>
  <%= link_to "Salir", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Entrar", new_user_session_path, data: {'turbo-method': :delete} %>
  <%= link_to "Crear cuenta", new_user_registration_path %>
<% end %>
<%= yield %>


<header class="bg-green-300">
<%= image_tag 'juan.png', alt: 'Proyectos Dev' %>
<h1><%= @page_title %></h1> 
</header>
<section class="flex">
<nav class="bg-green-300 p-6">
<ul class="text-white-300 leading-8">
<li><a href="/">Principal</a></li>
<li><a href="/projects/new">Agregar proyectos</a></li> 
<li><a href="/projects/">Imprimir proyectos</a></li>

</ul> </nav>
<main class="container mx-auto mt-4 px-5 flex"> <%= yield %>
      </main>
    </section>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 14, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-green-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Nombre:</strong>
    <%= project. title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Descripción:</strong>
    <%= project.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Image url:</strong>
    <%= project.image_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Valor de proyecto:</strong>
    <%= project.price %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Mostrar este  proyecto", project, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Editar este  proyecto', edit_project_path(project), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/projects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editar proyectos</h1>

  <%= render "form", project: @project %>

  <%= link_to "Mostrar proyecto", @project, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Regresar a proyectos", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-50 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center pb-8">
    <h1 class="mx-auto font-bold text-4xl" >Proyectos</h1>
  </div>  
  <table id="projects" class="mx-auto">
  <tfoot>
  <tr>  
    <td colspan="3">
    <div class="mt-8">
    <%= link_to 'Nuevo proyecto', new_project_path, class: "inline rounded-lg py-1 px-2 bg-green-500 text-black block font-medium" %>
  
    </div>
</td>
</tr>
</tfoot>
<tbody> 
<% @projects.each do |project| %>
  <tr class="<%= cycle('bg-green-50', 'bg-white') %>">
  <td class="px-2 py-3">
  <%= image_tag(project.image_url, class: 'w-40') %>
  </td>
  <td>
  <h1 class="text-xl font-bold mb-3"><%= project.title %></h1> <p>
  <%= truncate(strip_tags(project.description), length: 80) %>
  </p> </td>
  <td class="px-3"> <ul>
  <li>
  <%= link_to 'Mostrar', project, class: 'hover:underline' %>
</li>
<li>
<%= link_to 'Editar', edit_project_path(project),
class: 'hover:underline' %>
</li>
<li>
<%= link_to 'Eliminar', project, class: 'hover:underline',
    data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
      </li>
    </ul>
    </td>
    </tr>
  <% end %>
  </tbody>
  </table>
  </div>




  

app/views/projects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nuevo Proyecto</h1>

  <%= render "form", project: @project %>

  <%= link_to 'Regresar a proyectos', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @project %>

    <%= link_to 'Editar proyecto', edit_project_path(@project), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Eliminar proyecto', project_path(@project), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Regresar a proyectos', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/store/index.html.erb
<div class="w-full">
<% if notice.present? %>
<p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
<%= notice %> </p>
<% end %>
<h1 class="font-bold text-xl mb-6 pb-2 border-b-2"> Catalogo de proyectos
</h1>
<ul>
<% @projects.each do |project| %> <li class='flex mb-6'>
<%= image_tag(project.image_url, class: 'object-contain w-40 h-48 shadow mr-6') %>
<div>
<h2 class="font-bold text-lg mb-3"><%= project.title %></h2>
<p>
<%= sanitize(project.description) %> </p>
<div class="mt-3">
<p> Valor del proyecto: 
<%= project.price %> </p>
        </div>
       
        </div>
</li>

<% end %> 

</ul>
<%= link_to "Imprimir PDF" ,projects_url(@project)+".pdf" %>
</div>